name: Build Docker image, then push to Docker Hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
      
    - name: Push to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push $IMAGE_NAME
