name: Build Docker image, then push to Docker Hub
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  secret_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Scan for hardcoded secrets
      uses: docker://zricethezav/gitleaks:latest
      with:
        args: detect -s /github/workflow/ -v --redact
  
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ideaworksmedic/testimage
      
    - name: Scan with Trivy
      run: |
        export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        wget -q https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
        sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb
        trivy image ideaworksmedic/testimage --ignore-unfixed
      
    - name: Push to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push $IMAGE_NAME
